name: "AZURE Infra"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  provision-az-vm:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
          working-directory: ./terraform/azure

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      
      # Configure AWS credentials
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: 'us-east-1'

      # Configure AZURE  credentials
      - name: Login to Azure
        uses: azure/login@v1
        with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
         allow-no-subscriptions: false
        

      # Terraform Setup
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

#  Add SSH Key from GitHub Secrets
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" > ~/.ssh/devazure.pem
          echo "${{ secrets.AZURE_SSH_PUBLIC_KEY }}" > ./scripts/devazure.pem.pub
          chmod 600 ~/.ssh/devazure.pem
          echo "${{ secrets.AZURE_SSH_PUBLIC_KEY }}" >> ~/.ssh/authorized_keys

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

    # Save instance IPs and create inventory file for Ansible
      - name: Save instance IPs and create inventory
        run: |
          INSTANCE_IPS=$(terraform output -json public_ip_address)

          # Check if it's a JSON array or a string
          if echo "$INSTANCE_IPS" | jq -e 'if type == "string" then empty else . end' >/dev/null; then
            IP_LIST=$(echo "$INSTANCE_IPS" | jq -r '.[]')
          else
            IP_LIST=$(echo "$INSTANCE_IPS" | jq -r '.')
          fi

          # Create inventory.ini
          echo "[servers]" > inventory.ini
          echo "$IP_LIST ansible_user=devadmin ansible_ssh_private_key_file=~/.ssh/devazure.pem" >> inventory.ini

    

      #  Add SSH Key from GitHub Secrets
      # - name: Add SSH Key
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" > ~/.ssh/devazure.pem
      #     echo "${{ secrets.AZURE_SSH_PUBLIC_KEY }}" > /scripts/devazure.pem.pub
      #     chmod 400 ~/.ssh/devazure.pem
      #     echo "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" >> ~/.ssh/authorized_keys

      - name: Check SSH Key Format
        run: |
            sudo apt-get install libssl-dev
            cat ~/.ssh/devazure.pem
            openssl rsa -noout -modulus -in ~/.ssh/devazure.pem
 
      - name: Test SSH connection
        run: |
              INSTANCE_IP=$(terraform output -json public_ip_address | jq -r 'if type == "string" then . else .[0] end')
              ssh -vvv -o StrictHostKeyChecking=no -i ~/.ssh/devazure.pem devadmin@$INSTANCE_IP 'echo Hello from GitHub Actions'
                
    
      # Install Ansible
      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      #Run Ansible Playbook
      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini ./scripts/install_k3s.yml -vvv